# Generated by Django 5.2.7 on 2025-10-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='drawing_data',
            new_name='strokes',
        ),
    ]
