# Generated by Django 5.2.7 on 2025-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('room_id', 'user_name')},
            },
        ),
    ]
