services:
  # Django Backend Service
  - type: web
    name: collabboard-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p $PORT whiteboard_project.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DJANGO_SETTINGS_MODULE
        value: whiteboard_project.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: collabboard-db
          property: connectionString

  # React Frontend Service  
  - type: web
    name: collabboard-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npx serve -s build -l $PORT"
    envVars:
      - key: NODE_VERSION
        value: "18"

databases:
  - name: collabboard-db
    databaseName: collabboard
    user: collabboard